comment: off

coverage:
  status:
    patch:
      default:
        target: 80%
        threshold: 10%
        base: auto
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
  range: 50..100
  round: down
  precision: 2

ignore:
  - "backend/src/main/java/com/trip/companion/config/**/*"
  - "backend/src/main/java/com/trip/companion/repository/migration/**/*"
  - "backend/src/main/java/com/trip/companion/filter/DevCorsFilter.java"
  - "backend/src/main/java/com/trip/companion/TripCompanionApplication.java"