comment: off

coverage:
  status:
    patch:
      default:
        target: 80%
        threshold: 10%
        base: auto
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
  range: 50..100
  round: down
  precision: 2