spring:
  data:
    mongodb:
      port: &mongo_port 28000

mongo:
  embedded:
    enabled: true
    port: *mongo_port

mongock:
  changeLogsScanPackage:
    - com.trip.companion.repository.migration

jwt:
  secret: dev-secret
  refreshTokenExpirationInMs: 300000
  accessTokenExpirationInMs: 60000