server:
  port: 9000

spring:
  data:
    mongodb:
      database: trip-companion
      port: 27017

jwt:
  secret: ${random.uuid}
  refreshTokenExpirationInMs: 1209600000
  accessTokenExpirationInMs: 900000