server:
  port: 9000

spring:
  http:
    multipart:
      max-file-size: 5MB
  data:
    mongodb:
      database: trip-companion
      port: 27017

mongock:
  changeLogsScanPackage:
    - com.trip.companion.repository.migration

jwt:
  secret: ${random.uuid}
  refreshTokenExpirationInMs: 1209600000
  accessTokenExpirationInMs: 900000