spring:
  data:
    mongodb:
      port: 28000

mongo:
  embedded:
    enabled: true

mongock:
  changeLogsScanPackage:
    - com.trip.companion.repository.migration

jwt:
  secret: dev-secret
  refreshTokenExpirationInMs: 1_209_600_000
  accessTokenExpirationInMs: 900_000