name: Deploy to AWS

on:
  workflow_dispatch:

jobs:
  backendDeploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test
    - name: Deploy to the DEV AWS server
      uses: wlixcc/SFTP-Deploy-Action@1.1
      with:
        username: ubuntu
        server: ${{ secrets.AWS_DEV_SERVER_IP }}
        ssh_private_key: ${{ secrets.AWS_DEV_SSH_PRIVATE_KEY }}
        local_path: ./backend/build/libs/backend*.jar
        remote_path: /home/ubuntu
    - name: Restart service on AWS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_DEV_SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.AWS_DEV_SSH_PRIVATE_KEY }}
        script: |
          mv /home/ubuntu/backend*.jar /opt/trip-companion/
          ls -t1 /opt/trip-companion/backend-* | tail -n +2 | xargs rm
          sudo service trip-companion restart